# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        args: ["-l", "79"]
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.14'
    hooks:
    -   id: ruff